RuntimeType: Container
ServiceType: private
ArtifactSourceType: DockerCompose
ServiceBuildRegion: ap-southeast-1
RepoName: aliyun-computenest/quickstart-asktable
DockerComposeEnvPath: .env
RegionId: cn-hangzhou
CustomParameters:
- NoEcho: false
  Type: String
  AllowedPattern: ''
  Label: AI 大模型api-key
  ConstraintDescription: ''
  Name: LLM_API_KEY
  Description: '是以“asktable-”开头的字符串。登录 AskTable(https://cloud.asktable.com/?dialog=deployment) 获取'
DockerComposeYamlPath: docker-compose.yml
Owner: workhardliuzheng
Branch: main
Platform: github
