Service:
  RegionId: cn-hangzhou
  DeployType: ros
  OperationMetadata:
    CustomOperations:
      Actions:
      - TemplateNames:
        - ECS单机版
        Name: 升级askTable镜像版本
        Type: OOS
        TemplateUrl: 'oos.yaml'
        Operator: All
    StatusOperationConfigs:
    - TemplateName: ECS单机版
      SupportOperations:
      - Start
      - Stop
      - Restart
    SupportBackup: true
    ModifyParametersConfig:
    - TemplateName: ECS单机版
      Operation:
      - Name: 变更ECS实例规格
        Description: 变更ECS实例规格
        Type: Custom
        Parameters:
        - EcsInstanceType
      - Name: 变更ECS实例密码
        Description: 变更ECS实例密码
        Type: Custom
        Parameters:
        - InstancePassword
  DeployMetadata:
    SupplierDeployMetadata:
      SupplierTemplateConfigs:
      - Name: ECS单机版
        Url: 'ros_templates/template.yaml'
        ArchitectureDiagramUrl: 'resources/architecture/architecture.jpg'
        AllowedRegions:
        - ap-southeast-1
      ArtifactRelation:
        ecs_image_quickstart-asktable:
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: draft
    TemplateConfigs:
    - Name: ECS单机版
      Url: 'ros_templates/template.yaml'
      ArchitectureDiagramUrl: 'resources/architecture/architecture.jpg'
      AllowedRegions:
      - ap-southeast-1
  ServiceType: private
  ServiceInfo:
    # 英文版可以再配置Locale为en-US的服务信息
  - Locale: zh-CN
    Name: AskTable社区版
    ShortDescription: 
      AskTable.com是中国首家企业级表格智能体（TableAgentasaService）服务商，基于世界领先的大模型（比如通义千问、DeepSeek、GPT、Claude等）打造，专为企业提供基于自然语言的数据分析体验，广泛支持Excel、数据库、数据仓库和知识库的智能查询。用户无需懂SQL，只需用“说”的方式，即可获得实时数据洞察，广泛应用于运营、财务、人事、销售等业务场景。目前AskTable提供三种版本：SaaS在线版、本地部署（云端算力）、本地部署（本地算力），满足不同企业对数据隐私、安全和算力的需求。
    Image: 
      https://service-info-public.oss-cn-hangzhou.aliyuncs.com/1811606791208172/service-image/55051850-1077-41f3-8422-a5d4e54d09c9.jpg
    Softwares: []
  UpgradeMetadata:
    Description: 支持升级
    SupportUpgradeFromVersions: []
    SupportRollback: true
    UpgradeComponents:
    - Configuration
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: ecs_image_quickstart-asktable
    Description: quickstart-asktable EcsImage
    SupportRegionIds:
    - ap-southeast-1
    ArtifactBuildProperty:
      CodeRepo:
        Platform: github
        Owner: workhardliuzheng
        RepoName: aliyun-computenest/quickstart-asktable
        Branch: main
      RegionId: ap-southeast-1
      CommandType: RunShellScript
      CommandContent: |-
        mkdir -p /root/application
        if [ -e "/root/code/mysql_data" ]; then cp -r "/root/code/mysql_data" "/root/application/"; fi
        if [ -e "/root/code/.env" ]; then cp -r "/root/code/.env" "/root/application/"; fi
        if [ -e "/root/code/docker-compose.yml" ]; then cp -r "/root/code/docker-compose.yml" "/root/application/"; fi
        if [ -e "/root/code/asktable_data" ]; then cp -r "/root/code/asktable_data" "/root/application/"; fi
        cd /root/application
        sed -i 's/pull_policy: always/pull_policy: if_not_present/g' docker-compose.yml
        docker compose -f docker-compose.yml build 
        docker compose -f docker-compose.yml pull 2>&1 | stdbuf -oL grep -viE 'Downloading|sha256|extracting|KiB|Downloaded' || true;
